CFLAGS = -c -Wall
CC = g++
LIBS =  -lm
LIB = ../lib

all: server client

server: server.o tour.o reservation.o
        ${CC} server.o tour.o reservation.o -o server

server.o: server.cpp
        ${CC} ${CFLAGS} server.cpp
login.o:  login.cpp
        ${CC} ${CFLAGS} login.cpp
client: client.o 
        ${CC} client.o 

client.o: client.cpp
        ${CC} ${CFLAGS} client.cpp


clean:
        rm -f *.o client server